/* MTI_DPI */

/*
 * Copyright 2002-2020 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linuxaloem'
 */
#ifndef INCLUDED_MY_DPI
#define INCLUDED_MY_DPI

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
helloFromCpp(
    svLogic a);

DPI_LINK_DECL void
helloFromSV(
    svBit b);

#endif 
